### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pipperv** [zhangbaozhe/icg_ros#4]
Hi, i'm having an issue, after running `rosrun icg_ros icg_test_node -config_dir=src/icg_ros/config` i'm getting the next output on terminal:

`Viewer  already exists  
Segmentation fault (core dumped)`

How can I fix this? there is no GUI showing, just that

**Comment by zhangbaozhe** [comment]
I am sorry that I cannot reproduce your error. But it looks like that icg crashes when it tries to generate the view-point model. When you first run icg, if you do not have the viewpoint model, icg will generate two binary format models for you in the config folder.
